environments:
  dev:
    server:
      host: localhost
      port: 8080
    database:
      name: devdb
      username: devuser
      password: devpass

  uat:
    server:
      host: uat.example.com
      port: 8081
    database:
      name: uatdb
      username: uatuser
      password: uatpass

  prod:
    server:
      host: prod.example.com
      port: 80
    database:
      name: proddb
      username: produser
      password: prodpass
